[project]
name = "plastl"
version = "1.0.0"
description = "Plastl Mesh Converter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy<2",
    "pyqt5>=5.15.11",
    "trimesh>=4.6.8",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.13.0",
]
