name: Build and Release Plastl

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            irm https://astral.sh/uv/install.ps1 | iex
          else
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          fi

      - name: Install dependencies via uv
        run: |
          uv venv
          uv pip install -e .

      - name: Build app with PyInstaller
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            pyinstaller --windowed --icon=assets/plastl.icns plastl.py
            cd dist && zip -r plastl-macos-arm64.app.zip plastl.app
          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            pyinstaller --windowed --onefile plastl.py
            zip dist/plastl-linux-x64.zip dist/plastl
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            pyinstaller --windowed --onefile --icon=assets/plastl.ico plastl.py
            Compress-Archive -Path dist/plastl.exe -DestinationPath dist/plastl-windows-x64.zip
          fi
        shell: bash

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}